---
version: 0.0
os: linux
files:
  - source: /dist/index.html
    destination: /usr/share/nginx/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  ApplicationStart:
    - location: scripts/start_server.sh
