---
version: 0.0
os: linux
files:
  - source: /dist/index.html
    destination: /var/www/html/index.html
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  ApplicationStart:
    - location: scripts/start_server.sh
