version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir dist
      - cp index.html ./dist/
      - ls -la
artifacts:
  files:
    - dist/**/*
    - scripts/*
    - appspec.yml
